# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=64)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacti_app.User'),
        ),
        migrations.AddField(
            model_name='day',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacti_app.ScheduleBlock'),
        ),
    ]
