# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 17:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('schedule_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('schedule_desc', models.CharField(max_length=128)),
                ('start_time', models.TimeField(default=datetime.datetime(2016, 4, 19, 17, 22, 24, 244924, tzinfo=utc))),
                ('end_time', models.TimeField(default=datetime.datetime(2016, 4, 19, 17, 22, 24, 244966, tzinfo=utc))),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacti_app.Day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'')),
                ('status', models.BooleanField()),
                ('phone_number', models.IntegerField(max_length=11)),
                ('friends', models.ManyToManyField(related_name='_userhelper_friends_+', to='cacti_app.UserHelper')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
