# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleblock',
            old_name='description',
            new_name='schedule_description',
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='schedule_name',
            field=models.CharField(default=datetime.datetime(2016, 3, 21, 3, 50, 5, 968146, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='cacti_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 3, 21, 3, 50, 10, 479993, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
