# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cacti_app', '0002_auto_20160326_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'')),
                ('status', models.BooleanField()),
                ('phone_number', models.IntegerField(max_length=11)),
                ('friends', models.ManyToManyField(related_name='_userhelper_friends_+', to='cacti_app.UserHelper')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
