# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 17:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0002_auto_20160321_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='block',
            new_name='schedule_block',
        ),
        migrations.RemoveField(
            model_name='scheduleblock',
            name='schedule_description',
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='schedule_desc',
            field=models.CharField(default=datetime.datetime(2016, 3, 24, 17, 33, 0, 633000, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 24, 17, 32, 48, 744000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 24, 17, 32, 48, 744000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
