# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0003_auto_20160324_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleblock',
            name='id',
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 26, 23, 7, 2, 127844, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='schedule_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 26, 23, 7, 2, 127804, tzinfo=utc)),
        ),
    ]
