# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0003_auto_20160329_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 31, 2, 35, 1, 293740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 31, 2, 35, 1, 293697, tzinfo=utc)),
        ),
    ]
