# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0004_auto_20160419_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 5, 17, 34, 13, 107574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2016, 5, 5, 17, 34, 13, 107538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userhelper',
            name='picture',
            field=models.ImageField(upload_to='pfps/'),
        ),
    ]
