# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0004_auto_20160412_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 16, 18, 11, 31, 242559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2016, 4, 16, 18, 11, 31, 242520, tzinfo=utc)),
        ),
    ]
