# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0004_auto_20160326_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 26, 23, 14, 33, 370288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 26, 23, 14, 33, 370247, tzinfo=utc)),
        ),
    ]
