# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0005_auto_20160326_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleblock',
            name='user',
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 26, 23, 16, 51, 301010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(verbose_name=datetime.datetime(2016, 3, 26, 23, 16, 51, 300930, tzinfo=utc)),
        ),
    ]
