# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0004_auto_20160505_1328'),
        ('cacti_app', '0005_auto_20160505_1734'),
    ]

    operations = [
    ]
