# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cacti_app', '0007_auto_20160326_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 28, 13, 33, 31, 44000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 28, 13, 33, 31, 44000, tzinfo=utc)),
        ),
    ]
